#REPLACE USING YOUR WEBHOOK URL

webhookURL: "https://discord.com/api/webhooks/XXXXXX"

serverenable: "Server was enabled"
serverdisable: "Server was disabled"
#USE %plaeyr% to display name
diemessage: "%player% dies!"
